[build]
	functions = "netlify/functions"
	publish = "build" 
     command = "npm run build && mkdir -p netlify/functions/src/templates && cp src/templates/contactEmail.hbs netlify/functions/src/templates/contactEmail.hbs"

[functions]
    node_bundler = "esbuild"
    included_files = ["src/templates/contactEmail.hbs", "src/templates/contactEmail.css"]